### ISSUE TITLE
CORS Error on login

### ISSUE THREAD

**Issue by mavericksy** [kerberos-io/factory#10]
Hi,

The enterprise install throws a CORS error when attempting to login.
![kerberos_cors_error](https://user-images.githubusercontent.com/8345181/132120737-b0e7f1b0-fd02-40af-9e8a-82a30a3ed45c.png)

The API is just a subdomain of the factory domain.

**Comment by cedricve** [comment]
can you reach the api by by curling it or in the browser?

Kind regards,
Verstraeten Cédric

**Comment by mavericksy** [comment]
Curling the factory.domain.com works.
The api returns connection refused or not found.

![api_backend](https://user-images.githubusercontent.com/8345181/132121315-ccded812-91ce-4b7c-bb7e-bec8f6c06cce.png)
![curl_frontend](https://user-images.githubusercontent.com/8345181/132121316-0ef2e2c2-1a97-438e-b0fe-f7f56736fe29.png)

**Comment by Sebastien-Meiffren** [comment]
Hi
I had the issue while doing my install.
I've updated the configuration of nginx ... I'm trying to have it in a docker compose format therefore, my configuration is bit different : 
```
server
{
    listen 80;
    root /var/www/frontend;
    index index.html;
    location / {
        try_files $uri /index.html =404;
    }

    # Media: images, icons, video, audio, HTC
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Javascript and CSS files
    location ~* \.(?:css|js)$ {
        try_files $uri =404;
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    # Any route containing a file extension (e.g. /devicesfile.js)
    location ~ ^.+\..+$ {
        try_files $uri =404;
    }

    # I moved the API in the same domain name with an /api path. No more CORS issues
    location /api {
        proxy_pass http://127.0.0.1:8082;
    }
}
```

If you want to have it in a separate FQN, you need to add this in the API server configuration (still in NGINX)
```
  add_header 'Access-Control-Allow-Origin' '*' always; # if you are exposed on the internet, you will need to secure this line with the calling FQN
  add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
  add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
  add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
```

**Comment by cedricve** [comment]
By now should have been fixed, major changes have been added since this issue post.
