### ISSUE TITLE
Enterprise Edge Installation -  mongodb status pending 

### ISSUE THREAD

**Issue by gabeale** [kerberos-io/factory#6]
Hi,
I have tried several times (checking carefully the step by step commands at the link https://doc.kerberos.io/enterprise/installation-edge) to set up Kerberos Enterprise-Edge: facory and trafefik pods are running but mongodb is always "pending".
System is Ubuntu 18.04 LTS.
Any idea how to make it running?
Thank you in advance
Alex
![Schermata del 2021-01-02 10-19-21](https://user-images.githubusercontent.com/41168339/103454484-f6b14800-4ce4-11eb-865f-640b77d64159.png)

**Comment by cedricve** [comment]
hey you can use the kubectl describe po "podname" to see what is going wrong. I expect your pv is not properly setup.

**Comment by gabeale** [comment]
here you go:

root@alex-K52F:/home/alex# kubectl describe pod mongodb-6cbb4447b6-lrxhz
Name:           mongodb-6cbb4447b6-lrxhz
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/component=mongodb
                app.kubernetes.io/instance=mongodb
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=mongodb
                helm.sh/chart=mongodb-10.1.3
                pod-template-hash=6cbb4447b6
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/mongodb-6cbb4447b6
Containers:
  mongodb:
    Image:      docker.io/bitnami/mongodb:4.4.2-debian-10-r0
    Port:       27017/TCP
    Host Port:  0/TCP
    Liveness:   exec [mongo --eval db.adminCommand('ping')] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:  exec [mongo --eval db.adminCommand('ping')] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                    false
      MONGODB_ROOT_PASSWORD:            <set to the key 'mongodb-root-password' in secret 'mongodb'>  Optional: false
      ALLOW_EMPTY_PASSWORD:             no
      MONGODB_SYSTEM_LOG_VERBOSITY:     0
      MONGODB_DISABLE_SYSTEM_LOG:       no
      MONGODB_ENABLE_IPV6:              no
      MONGODB_ENABLE_DIRECTORY_PER_DB:  no
    Mounts:
      /bitnami/mongodb from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-token-8snst (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mongodb
    ReadOnly:   false
  mongodb-token-8snst:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-token-8snst
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  2m28s                default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  41m (x87 over 137m)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.


Thx

**Comment by cedricve** [comment]
your pvc is not properly configured. do you have a single node setup? and do you have changed the hostname to the nodes hostname?

**Comment by gabeale** [comment]
I'm not completely sure if I have used the right hostname, this is my config:

![Schermata del 2021-01-02 12-50-49](https://user-images.githubusercontent.com/41168339/103456750-5b769d80-4cf9-11eb-971c-03828cef96e7.png)

**Comment by cedricve** [comment]
can you print out your pvc `kubectl describe pvc` you will see what is going wrong.

**Comment by gabeale** [comment]
here you go!

Name:          mongodb
Namespace:     default
StorageClass:  local-storage
Status:        Pending
Volume:        
Labels:        app.kubernetes.io/component=mongodb
               app.kubernetes.io/instance=mongodb
               app.kubernetes.io/managed-by=Helm
               app.kubernetes.io/name=mongodb
               helm.sh/chart=mongodb-10.1.3
Annotations:   meta.helm.sh/release-name: mongodb
               meta.helm.sh/release-namespace: default
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       mongodb-6cbb4447b6-lrxhz
Events:
  Type     Reason              Age                   From                         Message
  ----     ------              ----                  ----                         -------
  Warning  ProvisioningFailed  58m (x402 over 158m)  persistentvolume-controller  storageclass.storage.k8s.io "local-storage" not found
  Warning  ProvisioningFailed  3m28s (x82 over 23m)  persistentvolume-controller  storageclass.storage.k8s.io "local-storage" not found

**Comment by cedricve** [comment]
Interesting what is your kubernetes version?

**Comment by gabeale** [comment]
typing _kubectl version_ I get this:
![Schermata del 2021-01-02 13-43-26](https://user-images.githubusercontent.com/41168339/103457581-d68f8200-4d00-11eb-9075-5a60a5f9385b.png)

**Comment by gabeale** [comment]
Dear Cedricve, any news so far?
Thanks in advance for support you will give.

**Comment by cedricve** [comment]
hey @gabeale, we might need to jump a short video call to clear this out. Can you also print out your nodes

`kubectl get nodes `

**Comment by gabeale** [comment]
Dear @cedricve thanks for availability. No problem for video call through Teams or equivalent, just tell me your preference. I tried once again to fresh install the Edge Enterprise following the procedure but situation in same.
I run kubectl get nodes command and got this:

![kubectl_get_nodes](https://user-images.githubusercontent.com/41168339/104514945-616e5780-55f2-11eb-836e-353cf911a5d8.PNG)

**Comment by gabeale** [comment]
Hi @cedricve, have you had the chance to review my situation? Thanks a lot

**Comment by lexustec** [comment]
@gabeale  I had a similar issue.
My issue was basically that the mongodb container didnt get up because of some persisten settings.

I removed the mongodb pod and removed the pv and also emptied the directory which was for the pv. after this it did work. I found that by loooking into the logs which stated auth failed and and and. now it works on my end. at least for this issue

**Comment by cedricve** [comment]
thanks @lexustec for sharing your feedback. @gabeale sadly im not able to reproduce..

**Comment by lexustec** [comment]
@cedricve i will prepare a blank machine and record the process or maybe a twitch stream. I try to reproduce the issue from user side.
Many things are different between blank machines and dev machines. ( i have a lot of issues to get the docker images running or even do the stand alone install ... but that is not point of this issue now )

**Comment by gabeale** [comment]
Hi guys, any news so far?
Thanks in advance :-)

**Comment by cedricve** [comment]
@lexustec managed to install it so we might need to look into it together @gabeale. Let me know when you are available.

**Comment by gabeale** [comment]
Anytime next week with the exception of Wednesday.
Thank you all for availability
Ciao

**Comment by gabeale** [comment]
Dear @lexustec please let us know when you are available for this issue. Thx in advance! 🙂

**Comment by lexustec** [comment]
Sorry for the late reply. I was busy. I am available basically. Cedric has me in discord. He can ping me there anytime.

**Comment by gabeale** [comment]
Dear friends, I'm also having discord account.
Just give me a ping when you are ready. Thx

**Comment by lexustec** [comment]
You can find me via lexarion#9146

**Comment by gabeale** [comment]
Thx, I'm gabeale#1980

**Comment by cedricve** [comment]
By now should have been fixed, major changes have been added since this issue post.
